export type PlayerData = {
    Name: string;
    Week1: number | null;
    Week2: number | null;
    Week3: number | null;
    Week4: number | null;
    Week5: number | null;
    Week6: number | null;
    Week7: number | null;
    Week8: number | null;
    StdDev?: number;
    Total: number;
    Average: number;
    WeeksPlayed: number;
    BestWeek: number;
    SecondBest: number;
    ThirdBest: number;
    FourthBest: number;
    SumOfBests: number;
};
